### ISSUE TITLE
Update github and cocumentation

### ISSUE THREAD

**Issue by timersys** [easydigitaldownloads/EDD-License-handler#10]
Hi! I think you should update this github repo and gist in http://docs.easydigitaldownloads.com/article/383-automatic-upgrades-for-wordpress-plugins or remove it. Because it's really an old version and many people could get it wrong

**Comment by dmgawel** [comment]
+1

**Comment by pippinsplugins** [comment]
We've removed the code here since it was severely out dated. Please refer to the main documentation.
