### ISSUE TITLE
Is the EDD_SL_Plugin_Updater.php file in this repo the latest one?

### ISSUE THREAD

**Issue by sudar** [easydigitaldownloads/EDD-License-handler#15]
Is the `EDD_SL_Plugin_Updater.php` present in this repo the latest one or the one present inside the edd-sample-plugin.zip that is part of Software Licensing addon the latest one?

I see that there are some changes that are in the file that is present in this repo that are not available in the one that is part of the sample plugin. But the version number of the class in the sample plugin is 1.6.2 while the version of the file present in this repo is just 1.6

It will be really nice if the latest version of `EDD_SL_Plugin_Updater.php` is available in a github repo so that we can easily pull the latest version as part of our plugin's build process.

**Comment by pippinsplugins** [comment]
Nope, this is out of date. I'll get it updated this week.

**Comment by sudar** [comment]
Thanks. And if possible please keep this repo upto date.

I am going to pull the file directly from this repo as part of my build process.

**Comment by sudar** [comment]
Is the repo upto date now?

**Comment by pippinsplugins** [comment]
It will be updated by the end of the week.

Watch out for a blog post on https://easydigitaldownloads.com/development

**Comment by pippinsplugins** [comment]
Updated!
