### ISSUE TITLE
sslverify false?

### ISSUE THREAD

**Issue by johnbillion** [easydigitaldownloads/EDD-License-handler#17]
What's the reason behind setting `sslverify` to false when [activating](https://github.com/easydigitaldownloads/EDD-License-handler/blob/d71dd8ecab248549948c9a6cc06c010fe4c33b97/EDD_License_Handler.php#L168) and [deactivating](https://github.com/easydigitaldownloads/EDD-License-handler/blob/d71dd8ecab248549948c9a6cc06c010fe4c33b97/EDD_License_Handler.php#L211) a license?

Ideally `sslverify` should never be set to false because it does not verify the remote server's SSL certificate. If there are server compatibility reasons for doing this, I'd love to hear them!

**Comment by pippinsplugins** [comment]
@johnbillion It was originally done because of an issue in WP core (I wish I could find the ticket). As far as I know, that issue is 100% resolved now and we should be able to safely remove it now.

**Comment by pippinsplugins** [comment]
This has been fixed in our main Software Licensing repository.
