### ISSUE TITLE
Auto Updates in the Background

### ISSUE THREAD

**Issue by wsenjer** [easydigitaldownloads/EDD-License-handler#19]
How can I implement my plugins to support auto-upgrade? I mean auto-upgrading in the background without any intervention from the user. 
Is this something can be done? Or even recommended?

**Comment by pippinsplugins** [comment]
@wsenjer At this time we do not have support for background updates. We will be considering it in the future but it's supported at this time.

**Comment by wsenjer** [comment]
@pippinsplugins 
Thank you Pippin, I'm looking forward to it. 
Do you recommend enabling the background updates by default in my plugins? I don't have the feeling that it would be a good idea. What do you think?

**Comment by pippinsplugins** [comment]
Depends on what the plugins are and what kind of updates you're releasing.
