### ISSUE TITLE
Pass current version number

### ISSUE THREAD

**Issue by shamim2883** [easydigitaldownloads/EDD-License-handler#21]
hi @pippinsplugins 
Please pass current version number when activate or check plugin and add a feature in your software licensing plugin where can capture this version. That way we can see which website using which version of our premium plugin. That can be shown for every license also in license table in wp admin. This will be very useful for keeping our premium plugin fresh. we will know which older version users are using, so that we can remove some code also.

**Comment by pippinsplugins** [comment]
It's on our todo list and is currently being tracked in our Software Licensing repository.

**Comment by shamim2883** [comment]
Hello again @pippinsplugins
Where is Software Licensing repository? Can i have access to that repository? I have some feature request for that extension. I may sometimes contribute some code also.

I have bought that extension and have valid license (if that helps).

**Comment by pippinsplugins** [comment]
It's a private repository, sorry.
