### ISSUE TITLE
Update EDD_SL_Plugin_Updater.php to 1.6.7

### ISSUE THREAD

**Issue by d4mation** [easydigitaldownloads/EDD-License-handler#22]
I have this Repo set as a Submodule so I can just pull in the latest version, but I noticed that this repo actually doesn't hold the latest version.

Edit: It is only a little bit out-of-date. I thought I saw it hadn't been updated in a year when I first opened the Issue.

https://easydigitaldownloads.com/development/2016/12/21/edd_sl_plugin_updater-class-updated-to-version-1-6-7/

**Comment by pippinsplugins** [comment]
Done: https://github.com/easydigitaldownloads/EDD-License-handler/commit/85c6c8310d713e3ca38edfa811ae900f08bf7d21

**Comment by d4mation** [comment]
Thanks @pippinsplugins!
