### ISSUE TITLE
 Uncaught Error: Cannot use object of type stdClass as array in wp-admin\includes\plugin-install.php:500

### ISSUE THREAD

**Issue by burhandodhy** [easydigitaldownloads/EDD-License-handler#26]
On clicking "View version xx details" the second time this error is produced.

Steps to produce an error.
1) Click on "View version xx details." it will work fine.
2) Click on "View version xx details."  again and this error will come.

**Reason.**
1) The first time it fetches the data on which the "sections" property of object consists arrays. Like this

`				["sections"]=>	array(2) {
				    ["description"]=> "***"
				    ["changelog"]=> "***" 
					}`

Then returning data encoded in JSON and stored in options table.

2) On the second click stored data get fetched and decoded back to the object and here is a problem the  "sections" property also convert into an object and Fatal Error come. 

`					["sections"]=>
				   object(stdClass)#771 (2) {
				     ["description"]=>"**"
				     ["changelog"]=>"**"
					 }`

**Temporary Solution:**
if we pass 3 parameters of json_decode() that, is depth to 1 than it didn't  convert the nested arrays into an object 

`json_decode( $cache['value'], false, 1 )`

**Problem After this**
 Plugins stop showing the update notices.

**Comment by pippinsplugins** [comment]
This is fixed in Software Licensing 3.5, which we're releasing later this week.

**Comment by pippinsplugins** [comment]
This is fixed in Software Licensing 3.5, which we're releasing later this week.

**Comment by unoframille** [comment]
I have the same problem with version 3.5.3

**Comment by hiddenpearls** [comment]
@pippinsplugins This is still happening with me too. It was fixed for a while but it is still appearing in SL 3.5.4

**Comment by pippinsplugins** [comment]
Did you update the class to 1.6.10?

**Comment by unoframille** [comment]
Perfect, thanks
