### ISSUE TITLE
Invalid argument supplied for foreach() in plugin screen

### ISSUE THREAD

**Issue by champsupertramp** [easydigitaldownloads/EDD-License-handler#32]
I'm getting the following warning on plugin screen:
`Warning: Invalid argument supplied for foreach() in /wp-content/plugins/myplugin/EDD_SL_Plugin_Updater.php on line 371 `

Adding this in the condition removes the warning: 
`if( ! empty( $request ) && is_array( $request ) ) {`
in https://github.com/easydigitaldownloads/EDD-License-handler/blob/master/EDD_SL_Plugin_Updater.php#L370

**Comment by pippinsplugins** [comment]
I've just pushed up version 1.6.11 that fixes this problem https://github.com/easydigitaldownloads/EDD-License-handler/commit/edbb8526741ffcb445670d6563a0757a1b39dbc0
