### ISSUE TITLE
Warning: Invalid argument supplied for foreach() on WooCommerce System Status Page

### ISSUE THREAD

**Issue by burhandodhy** [easydigitaldownloads/EDD-License-handler#34]
Hi,
I'm getting this error on WooCommerce 3  System Status Page.

`Warning: Invalid argument supplied for foreach() in \wp-content\plugins\my-plugin\lib\EDD_SL_Plugin_Updater.php on line 282`

**Comment by jordymeow** [comment]
Hi,

Check my pull here:
https://github.com/easydigitaldownloads/EDD-License-handler/pull/33/commits/8cf926158694b1c1942a82c058ec7405763eab51

That fixes the issue :)

**Comment by hiddenpearls** [comment]
@jordymeow Thank you. 
@pippinsplugins Can you please check his pull request and merge it. So, we could use it in our products ?

**Comment by pippinsplugins** [comment]
Merged. We had actually fixed that a few days back, just forgot to update the version here.

**Comment by burhandodhy** [comment]
@pippinsplugins  the error remain same even after updating the latest code

http://prntscr.com/eyzr1d

**Comment by pippinsplugins** [comment]
We ended up pushing additional fixes for this. Please use 1.6.12 of the updater.
