### ISSUE TITLE
Need to check if $_data->sections is null before foreach in EDD_SL_Plugin_Updater

### ISSUE THREAD

**Issue by yoancutillas** [easydigitaldownloads/EDD-License-handler#35]
Hello,

In EDD_SL_Plugin_Updater, line 282, please add a check before the foreach because if $_data->sections is null it causes an error.

```php
// Convert sections into an associative array, since we're getting an object, but Core expects an array.
if ( isset( $_data->sections ) && ! is_array( $_data->sections ) ) {
    $new_sections = array();
        if( $_data->sections ) {
            foreach ( $_data->sections as $key => $value ) {
                $new_sections[ $key ] = $value;
            }
        }

    $_data->sections = $new_sections;
}
```

You can display the error if you have 
- include EDD_SL_Plugin_Updater on admin_init hook
- woocommerce installed,
- a theme with obsolete WC template pages, 
then go to WC status system page and the errors shows.

(WP 4.7.3, WC 3.0.3, EDD_SL_Plugin_Updater 1.6.11, theme: accesspress-store 2.1.7)

But I guess this error can happen with other configurations since 'plugin_api' filter can return false.

**Comment by pippinsplugins** [comment]
@yoancutillas which version of the updater class are you using?

**Comment by yoancutillas** [comment]
I am using  EDD_SL_Plugin_Updater 1.6.11
The 'foreach' I mentionned is line 282.

**Comment by hiddenpearls** [comment]
@pippinsplugins We faced this issue too in one of our client sites. They were using outdated/obsolete WooCommerce templates. 

Can you please take a look and provide the fix. Thanks.

**Comment by pippinsplugins** [comment]
It's been fixed. You just need to use 1.6.12 of the updater.
