### ISSUE TITLE
Add EDD_Theme_Updater Class to this repo

### ISSUE THREAD

**Issue by d4mation** [easydigitaldownloads/EDD-License-handler#42]
Right now this Repo could be packaged with a Plugin to sell on an EDD Store to ensure the necessary Classes exist, but not a Theme. Having the Theme Updater class here could be convenient.

https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/master/samples/edd-sample-theme/updater/theme-updater-class.php

**Comment by pippinsplugins** [comment]
@d4mation We've closed this repo since all of the code management for the updater files is handled inside of our Software Licensing repo. Please see the main readme for more https://github.com/easydigitaldownloads/EDD-License-handler
